version: '3.8'

services:
  mqtt:
    image: eclipse-mosquitto:latest
    container_name: mqtt
    ports:
      - "1883:1883"
    volumes:
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log
      - ./mqtt/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
    # healthcheck:
    #   test: ["CMD", "mosquitto_sub", "-h", "localhost", "-t", "test", "-C", "1"]
    #  interval: 30s
    #  retries: 3

  influxdb:
    image: influxdb:2.7
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=phy-lab
    volumes:
      - influxdb_data:/var/lib/influxdb2
    #healthcheck:
    #  test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
    #  interval: 30s
    #  retries: 3

  telegraf:
    image: telegraf:latest
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    depends_on:
      - mqtt
      - influxdb

  sensor-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sensor-app
    depends_on:
      - mqtt
      - influxdb
    devices:
      - "/dev/gpiomem"
      - "/dev/mem"
    privileged: true

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
#grafana - admin -admin 
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    devices:
      - "/dev/gpiomem:/dev/gpiomem"
      - "/dev/mem:/dev/mem"
    privileged: true
    volumes:
      - node_red_data:/data
    environment:
      - ARCH=arm64
    group_add:
    - 993
    depends_on:
      - mqtt
      - influxdb

volumes:
  mosquitto_data:
  mosquitto_config:
  mosquitto_log:
  influxdb_data:
  telegraf_data:
  grafana_data: 
  node_red_data:
